feat(api): added api for request, cancel and send user consent code to AMT
open-amt-cloud-toolkit/mps pull request #332
Opened 2021-08-20 19:02 UTC by madhavilosetty-intel

AMT

AB#3455

2021-08-23 18:15 UTC, brianosburn-intel approved these changes

2021-08-25 16:41 UTC, rsdmike requested changes

2021-08-25 16:41 UTC, rsdmike commented on src/routes/amt/userConsent/sendUserConsentCode.ts
> +        log.error(`Fail to send user consent code for guid : ${guid}.`)
if i enter a wrong code, i see this message. But i'm guessing it didnt fail to send, its just incorrect. I think we should make that distinctions and send back the right error, something like invalid code, please try again, and re-prompt the dialog box.

2021-08-25 16:41 UTC, rsdmike commented on src/routes/amt/userConsent/sendUserConsentCode.ts
> +        log.error(`Fail to send user consent code for guid : ${guid}.`)
Additionally, after the wrong code, and i try again it gives me an error, i would have expected a new prompt.

2021-08-25 16:41 UTC, rsdmike commented on src/routes/amt/userConsent/cancelUserConsentCode.ts
> +/*********************************************************************
in terms of naming of these files, i think we can simplify a bit to just cancel.ts since its under a userconsent folder. Same for the others

2021-08-30 15:42 UTC, rsdmike approved these changes

2021-08-31 16:44 UTC, merged