4552 eventlog
open-amt-cloud-toolkit/mps pull request #463
Opened 2021-12-13 19:01 UTC by madhavilosetty-intel

## PR Checklist

- [ ] Unit Tests have been added for new changes
- [ ] API tests have been updated if applicable
- [ ] All commented code has been removed
- [ ] If you've added a dependency, you've ensured license is compatible with Apache 2.0 and clearly outlined the added dependency.

## What are you changing?

## Anything the reviewer should know when reviewing this PR?

### If the there are associated PRs in other repositories, please link them here (i.e. open-amt-cloud-toolkit/repo#365 )

2021-12-14 15:51 UTC, rsdmike requested changes

2021-12-14 15:51 UTC, rsdmike commented on src/amt/amt/AMT.ts
> +  MessageLog = (method: Methods.GET_RECORDS, messageId: string): string => {
Do you have a test for this?

2021-12-14 18:30 UTC, madhavilosetty-intel commented on src/amt/amt/AMT.ts
> +  MessageLog = (method: Methods.GET_RECORDS, messageId: string): string => {
added

2021-12-14 21:09 UTC, rsdmike requested changes

2021-12-14 21:09 UTC, rsdmike commented on src/routes/amt/eventLog.test.ts
> +  it('should get system firmware started', () => {
is this the right title?

2021-12-14 21:09 UTC, rsdmike commented on src/routes/amt/eventLog.test.ts
> +  it('should return system firware error', () => {
firware => firmware

2021-12-14 21:14 UTC, madhavilosetty-intel commented on src/routes/amt/eventLog.test.ts
> +  it('should return system firware error', () => {
corrected

2021-12-15 01:50 UTC, rsdmike approved these changes

2021-12-15 15:23 UTC, merged