refactor(mps): Input validation checks in APFProcessor for max size
open-amt-cloud-toolkit/mps pull request #594
Opened 2022-04-20 18:28 UTC by tim-shockley

closes AB#6610

## PR Checklist

- [ ] Unit Tests have been added for new changes
- [ ] API tests have been updated if applicable
- [ ] All commented code has been removed
- [ ] If you've added a dependency, you've ensured license is compatible with Apache 2.0 and clearly outlined the added dependency.

## What are you changing?

## Anything the reviewer should know when reviewing this PR?

### If the there are associated PRs in other repositories, please link them here (i.e. open-amt-cloud-toolkit/repo#365 )

2022-04-22 16:07 UTC, matt-primrose commented on src/amt/APFProcessor.ts
> +  SendChannelOpenConfirmation: (socket: CIRASocket,
can we keep the function parameters on a single line?

2022-04-22 16:08 UTC, matt-primrose commented on src/amt/APFProcessor.ts
> +  SendChannelOpen: (socket: CIRASocket,
can we keep the function parameters on a single line?

2022-04-22 16:13 UTC, matt-primrose commented on src/amt/APFProcessor.ts
> +      logger.error(`${messages.DATA_NO_CHANNEL_ID} ${recipientChnlId}`)
Can we spell out recipientChnlId so that it is more clearly human readable?  ex. recipientChannelId

2022-04-22 16:15 UTC, matt-primrose commented on src/amt/APFProcessor.ts
> +    parseIndex += chnlDataLen
please spell out the entire word for variables.  Makes the code easier to read.  chnl should be channel.  len should be length, etc.

2022-04-22 16:18 UTC, tim-shockley commented
umm, I'm gonna pushback on this one a bit.
It was way off the edge of my IDE and I don't like code wrapping or small text or not being able to see all the code and needing to scroll.
Maybe it would be better if if the parameters aligned under each other on wrap?

That being said, if single line calls are what the team wants and is expected formatting then I can readjust my formatting rules.
Does this apply to appended strings and other potential mutliline situations?


From: Matt Primrose ***@***.***>
Sent: Friday, April 22, 2022 09:08
To: open-amt-cloud-toolkit/mps ***@***.***>
Cc: Shockley, Timothy ***@***.***>; Author ***@***.***>
Subject: Re: [open-amt-cloud-toolkit/mps] refactor(mps): Input validation checks in APFProcessor for max size (PR #594)


@matt-primrose commented on this pull request.

________________________________

In src/amt/APFProcessor.ts<https://github.com/open-amt-cloud-toolkit/mps/pull/594#discussion_r856378091>:

>      )

   },



-  SendChannelOpen: (socket: CIRASocket, direct: boolean, channelid: number, windowSize: number, target: string, targetPort: number, source: string, sourcePort: number

-  ): void => {

+  SendChannelOpen: (socket: CIRASocket,

can we keep the function parameters on a single line?

—
Reply to this email directly, view it on GitHub<https://github.com/open-amt-cloud-toolkit/mps/pull/594#pullrequestreview-950304757>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AK374CN2UCCY7DOL6GOIDILVGLFG3ANCNFSM5T44K2FA>.
You are receiving this because you authored the thread.Message ID: ***@***.***>

2022-04-22 16:22 UTC, matt-primrose commented on src/amt/APFProcessor.ts
> +      logger.warn(`${messages.MPS_WARN_RESERVED_VALUE}, ${reserved.toString()}`)
Can the MPS do anything about this if we hit this?

2022-04-22 16:39 UTC, matt-primrose commented on src/amt/APFProcessor.ts
> +      String.fromCharCode(0)
why aren't we using common.ShortToStr(0) here as well?

2022-04-22 16:52 UTC, tim-shockley commented
API specifies the field lists it as 1 byte and Common.ShortToStr to me implies 2 bytes even though I realize that number 0 will convert to '0' as a char code. Suppose it's the embedded C/C++ background coming out.

From: Matt Primrose ***@***.***>
Sent: Friday, April 22, 2022 09:40
To: open-amt-cloud-toolkit/mps ***@***.***>
Cc: Shockley, Timothy ***@***.***>; Author ***@***.***>
Subject: Re: [open-amt-cloud-toolkit/mps] refactor(mps): Input validation checks in APFProcessor for max size (PR #594)


@matt-primrose commented on this pull request.

________________________________

In src/amt/APFProcessor.ts<https://github.com/open-amt-cloud-toolkit/mps/pull/594#discussion_r856401061>:

> @@ -561,9 +800,9 @@ const APFProcessor = {

     APFProcessor.Write(

       socket,

       String.fromCharCode(APFProtocol.USERAUTH_FAILURE) +

-        Common.IntToStr(8) +

-        'password' +

-        Common.ShortToStr(0)

+      Common.IntToStr(8) +

+      'password' +

+      String.fromCharCode(0)

why aren't we using common.ShortToStr(0) here as well?

—
Reply to this email directly, view it on GitHub<https://github.com/open-amt-cloud-toolkit/mps/pull/594#pullrequestreview-950338284>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AK374CLC2EGNUUCCQRSXGBDVGLI6DANCNFSM5T44K2FA>.
You are receiving this because you authored the thread.Message ID: ***@***.***>

2022-04-22 16:55 UTC, rsdmike requested changes
Ok, this is A LOT more changes than I think the story was asking for.  For reference, this https://github.com/Ylianst/MeshCentral/commit/1bb1dd0f59ba920f7f4e9db37a838e16ee15e178 is really what the story was asking for.  Overall, I like that you used the spec to enhance the implementation. However, I think creating ENUMs with constant values would be a more concise way to write the code, provide meaning and context, and avoid the increase in the lines of code.

2022-04-22 16:55 UTC, rsdmike commented on src/amt/APFProcessor.ts
> +      String.fromCharCode(0)
I think we should leave this with Common.ShortToStr(0)

2022-04-22 16:55 UTC, rsdmike commented on src/amt/APFProcessor.ts
> +  disconnect: (socket: CIRASocket, dataLen: number, data: string): number => {
In general, we tend to prefer full non-abbreviated variable name. So instead of `dataLen`, we'd do `dataLength`

2022-04-22 16:55 UTC, rsdmike commented on src/amt/APFProcessor.ts
> +    const reserved: number = Common.ReadShort(data, parseIndex)
I'm not sure why this was added -- we don't use or need this information, why parse it out?

2022-04-22 16:55 UTC, rsdmike commented on src/amt/APFProcessor.ts
> +    const recipientChnlId: number = Common.ReadInt(data, parseIndex)
`recipientChnlId` should be `recipientChannelId`

2022-04-22 16:55 UTC, rsdmike commented on src/amt/APFProcessor.ts
> +    const chnlDataLen: number = Common.ReadInt(data, parseIndex)
`chnlDataLen` shoudl be `channelDataLength`

2022-04-22 16:55 UTC, rsdmike commented on src/amt/APFProcessor.ts
> +    const recipientChnlId: number = Common.ReadInt(data, parseIndex)
recipientChnlId

2022-04-22 16:55 UTC, rsdmike commented on src/amt/APFProcessor.ts
> +    const cirachannel = socket.tag.channels[recipientChnlId]
recipientChannelld

2022-04-22 16:55 UTC, rsdmike commented on src/amt/APFProcessor.ts
> +    cirachannel.amtchannelid = senderChnlId
`senderChannelId`

2022-04-22 16:55 UTC, rsdmike commented on src/amt/APFProcessor.ts
> +    if (dataLen < 5) return 0
why did this change from 5 to 33?

2022-04-22 16:55 UTC, rsdmike commented on src/amt/APFProcessor.ts
> +    const chnlTypeLen: number = Common.ReadInt(data, parseIndex)
channelTypeLength

2022-04-22 16:55 UTC, rsdmike commented on src/amt/APFProcessor.ts
> +    if (dataLen < 5) {
why did this change from 14?

2022-04-22 16:55 UTC, rsdmike commented on src/amt/APFProcessor.ts
> +      const originatorAddrLen = Common.ReadInt(data, parseIndex)
originatorAddressLength

2022-04-22 16:55 UTC, rsdmike commented on src/amt/APFProcessor.ts
> +      const udpMsgLen = Common.ReadInt(data, parseIndex)
udpMessageLength

2022-04-22 16:55 UTC, rsdmike commented on src/amt/APFProcessor.ts
> +    parseIndex += 16
For all of these functions, the parseIndex adds a lot more lines of code for not much increase in readability at the expense of unnecessary computations. I get that it lines up with the length values, but the previous values lined up with the offset values.

2022-04-22 16:55 UTC, rsdmike commented on src/amt/APFProcessor.ts
> +    parseIndex += 4
unnecessary additions, why not += 8?

2022-04-22 22:29 UTC, closed without merging

2022-10-11 08:25 UTC, tim-shockley commented
to align with the API and checking fields as they are parsed instead of having just the 'magic' number at the begining (for almost every method)
additional checks are added later, the overall logic is still the same.

From: Matt Primrose ***@***.***>
Sent: Friday, April 22, 2022 09:19
To: open-amt-cloud-toolkit/mps ***@***.***>
Cc: Shockley, Timothy ***@***.***>; Author ***@***.***>
Subject: Re: [open-amt-cloud-toolkit/mps] refactor(mps): Input validation checks in APFProcessor for max size (PR #594)


@matt-primrose commented on this pull request.

________________________________

In src/amt/APFProcessor.ts<https://github.com/open-amt-cloud-toolkit/mps/pull/594#discussion_r856385970>:

>    },



-  channelOpen: (socket: CIRASocket, length: number, data: string): number => {

-    if (length < 33) return 0

-    const ChannelTypeLength: number = Common.ReadInt(data, 1)

-    if (length < 33 + ChannelTypeLength) return 0

+  channelOpen: (socket: CIRASocket, dataLen: number, data: string): number => {

+    if (dataLen < 5) return 0

Why did the length check change from 33 to 5 on this?

—
Reply to this email directly, view it on GitHub<https://github.com/open-amt-cloud-toolkit/mps/pull/594#pullrequestreview-950315735>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AK374CNNNWPT5B6SVTXPB43VGLGPRANCNFSM5T44K2FA>.
You are receiving this because you authored the thread.Message ID: ***@***.***>