unprovision
open-amt-cloud-toolkit/mps pull request #696
Opened 2022-10-06 18:38 UTC by Walt-Intel

## PR Checklist

- [ ] Unit Tests have been added for new changes
- [ ] API tests have been updated if applicable
- [ ] All commented code has been removed
- [ ] If you've added a dependency, you've ensured license is compatible with Apache 2.0 and clearly outlined the added dependency.

## What are you changing?

## Anything the reviewer should know when reviewing this PR?

### If the there are associated PRs in other repositories, please link them here (i.e. open-amt-cloud-toolkit/repo#365 )

2022-10-11 21:43 UTC, matt-primrose commented on src/amt/DeviceAction.ts
> +  async unprovisionDevice (): Promise<Common.Models.Envelope<any>> {
@Walt-Intel Can you add the following test to the deviceAction.test.ts
`describe('unprovision amt', () => {
    it('should return response from AMT', async () => {
      sendSpy.mockResolvedValueOnce({Envelope:null})
      const result = await device.unprovisionDevice()
      expect(result).toBe(null)
    })
  })`

2022-10-11 21:44 UTC, matt-primrose commented on src/utils/SecretManagerService.ts
> +    const basePath = Environment.Config.secrets_path.replace('/data/', '/metadata/')
@Walt-Intel can you add the following test to secretManagerService.test.ts:
`test('should remove device from secret store', async () => {
  const deleteSecretAtPathSpy = jest.spyOn(secretManagerService, 'deleteSecretAtPath').mockResolvedValue(null)
  const result = await secretManagerService.deleteSecretAtPath('test')
  expect(deleteSecretAtPathSpy).toHaveBeenCalledWith('test')
  expect(result).toBe(null)
})`

2022-10-11 21:45 UTC, matt-primrose requested changes
See comments that address code coverage gaps on changes

2022-10-11 22:51 UTC, rsdmike requested changes

2022-10-11 22:51 UTC, rsdmike commented on src/routes/amt/deactivate.ts
> +      res.status(200).json({ status: 'SUCCESS' })
Can you also add the removal of the device from memory like we talked about in planning. Something like
`delete devices[guid]`

2022-10-12 17:12 UTC, matt-primrose approved these changes
Good from my point of view.  Implement @rsdmike comment and good to merge!

2022-10-17 17:56 UTC, rsdmike approved these changes

2022-10-19 17:51 UTC, matt-primrose submitted a review, later dismissed

2022-10-21 20:52 UTC, rsdmike commented on src/utils/secretManagerService.test.ts
> +  expect(gotDeleteSpy).toHaveBeenCalled()
only thing i would change here is to ensure the call was made with what is expected. So:

``` suggestion
expect(gotDeleteSpy).toHaveBeenCalledWith('test',{ prefixUrl: 'theexpectedurl'})
```

2022-10-21 21:00 UTC, matt-primrose submitted a review, later dismissed

2022-10-21 22:30 UTC, madhavilosetty-intel approved these changes

2022-10-21 23:48 UTC, closed without merging